//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ID { get; set; }
        public int IDSala { get; set; }
        public int IDEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
